spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/safetrip'    # H2 DB 연결 주소 (Embedded Mode)
    username: sa       # H2 DB 접속 ID (사용자 지정)
    password:         # H2 DB 접속 PW (사용자 지정)

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

cloud:
  aws:
    credentials:
      access-key: REMOVED
      secret-key: REMOVED
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket-name: safetrip-bucket

