spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
    defer-datasource-initialization: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always  # prod에서는 DB, Redis 상태까지 확인

oci:
  storage:
    access-key: ${OCI_ACCESS_KEY}
    secret-key: ${OCI_SECRET_KEY}
    endpoint: ${OCI_STORAGE_ENDPOINT}   # https://{namespace}.compat.objectstorage.{region}.oraclecloud.com
    region: ${OCI_REGION}
    bucket-name: ${OCI_BUCKET_NAME}
    base-path: ${OCI_BASE_PATH}
