plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.swkim'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	implementation 'javax.xml.bind:jaxb-api:2.3.1'
	implementation 'com.sun.xml.bind:jaxb-impl:2.3.1'
	implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'

	// oci object storage (s3 compatible)
	implementation 'com.amazonaws:aws-java-sdk-s3:1.12.767'

	// swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'com.auth0:java-jwt:4.5.0'

	// redis
	implementation("org.springframework.boot:spring-boot-starter-data-redis")



	// logging
	implementation 'net.logstash.logback:logstash-logback-encoder:7.4'

	// actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// aop
	implementation 'org.springframework.boot:spring-boot-starter-aop'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	runtimeOnly 'com.mysql:mysql-connector-j'
}

bootRun {
	def envFile = file('.env')
	if (envFile.exists()) {
		envFile.eachLine { line ->
			if (line && !line.startsWith('#') && line.contains('=')) {
				def parts = line.split('=', 2)
				environment(parts[0].trim(), parts[1].trim())
			}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
	jvmArgs '-Xshare:off' // JVM 아규먼트 설정
}
